name: Documentation
# modified from GLM
env:
  JULIA_PKG_SERVER: https://github.com/alexpkeil1/EpiRegistry.git
concurrency:
  group: ${{ github.head_ref }}.docs
  cancel-in-progress: true
on:
  push:
    branches:
      - 'main'
      - 'gh-pages'
    tags: '*'
  pull_request:
jobs:
  Documenter:
    permissions:
      contents: write
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: julia-actions/julia-buildpkg@latest
        with:
          localregistry: |
            https://github.com/alexpkeil1/EpiRegistry.git
      - uses: julia-actions/julia-docdeploy@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
            
